const columns = [
    { name: "Serial No.", uid: "serial", sortable: true },
    { name: "Vehicle Number", uid: "vehicleNumber", sortable: true },
    { name: "Name", uid: "name", sortable: true },
    { name: "Status", uid: "status", sortable: true },
    { name: "Spot", uid: "spot", sortable: true },
    { name: "Fee", uid: "fee", sortable: true },
    { name: "Vehicle Type", uid: "vehicleType", sortable: true },
    { name: "Date|Time", uid: "dateTime", sortable: true },
    { name: "Payment Mode", uid: "paymentMode", sortable: true }, // Added Payment Mode column
    // { name: "Actions", uid: "actions" },
  ];
  
  const vehicles = [
    {
      serial: 1,
      vehicleNumber: "ABC123",
      name: "John Doe",
      status: "InRoute",
      spot: "A1",
      fee: "₹200",
      vehicleType: "Car",
      dateTime: "2024-09-07 10:30 AM",
      paymentMode: "Online",
    },
    {
      serial: 2,
      vehicleNumber: "XYZ456",
      name: "Jane Smith",
      status: "Parked",
      spot: "B2",
      fee: "₹150",
      vehicleType: "Bike",
      dateTime: "2024-09-07 11:00 AM",
      paymentMode: "Cash", 
    },
    {
        serial: 3,
        vehicleNumber: "XYZ456",
        name: "Jane Smith",
        status: "Parked",
        spot: "B2",
        fee: "₹150",
        vehicleType: "Bike",
        dateTime: "2024-09-07 11:00 AM",
        paymentMode: "Online", 
      },
      {
        serial: 4,
        vehicleNumber: "XYZ456",
        name: "Jane Smith",
        status: "Parked",
        spot: "B2",
        fee: "₹150",
        vehicleType: "Bike",
        dateTime: "2024-09-07 11:00 AM",
        paymentMode: "Cash", 
      },
      {
        serial: 5,
        vehicleNumber: "XYZ456",
        name: "Jane Smith",
        status: "Parked",
        spot: "B2",
        fee: "₹150",
        vehicleType: "Bike",
        dateTime: "2024-09-07 11:00 AM",
        paymentMode: "Online", 
      },
      {
        serial: 6,
        vehicleNumber: "XYZ456",
        name: "Jane Smith",
        status: "Parked",
        spot: "B2",
        fee: "₹150",
        vehicleType: "Bike",
        dateTime: "2024-09-07 11:00 AM",
        paymentMode: "Cash", 
      },
      {
        serial: 7,
        vehicleNumber: "XYZ456",
        name: "Jane Smith",
        status: "Parked",
        spot: "B2",
        fee: "₹150",
        vehicleType: "Bike",
        dateTime: "2024-09-07 11:00 AM",
        paymentMode: "Online", 
      },
      {
        serial: 8,
        vehicleNumber: "XYZ456",
        name: "Jane Smith",
        status: "Parked",
        spot: "B2",
        fee: "₹150",
        vehicleType: "Bike",
        dateTime: "2024-09-07 11:00 AM",
        paymentMode: "Cash", 
      },
  ];  

export { columns, vehicles };
