import './global.css';
import Nav from './components/Nav';

export const metadata = {
  title: 'Welcome to admin-template',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Nav/>
        {children}
        </body>
    </html>
  );
}
